#!/bin/bash

# Copyright 2018-present, Yudong (Dom) Wang
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# chkconfig: 345 99 01
# description: holer

### BEGIN INIT INFO
# Provides:          holer.service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start holer daemon at boot time
# Description:       Enable holer service provided by daemon.
### END INIT INFO

# -----------------------------------------------------------------------------
# Holer Script
# -----------------------------------------------------------------------------

JAVA_BIN=$JAVA_HOME/bin/java

HOLER_OK=0
HOLER_ERR=1
HOLER_PID=""

HOLER_HOME_DIR="/opt/holer"
HOLER_CLIENT_DIR=$HOLER_HOME_DIR/holer-client
HOLER_LOG_DIR=$HOLER_CLIENT_DIR/logs

HOLER_LOG=$HOLER_LOG_DIR/holer-client.log
HOLER_APP=$HOLER_CLIENT_DIR/holer-client.jar
HOLER_ARCH=`uname -m`
HOLER_ARM=""

# Source function library
INIT_FUNCTIONS="/etc/init.d/functions"
if [ -f $INIT_FUNCTIONS ]; then
    . $INIT_FUNCTIONS
fi

if [ ! -d $HOLER_LOG_DIR ]; then
    mkdir -p $HOLER_LOG_DIR
fi

arm()
{
    HOLER_ARM=$(echo $HOLER_ARCH | grep "arm")
    if [ "$HOLER_ARM" = "" ]; then
        HOLER_ARM=$(echo $HOLER_ARCH | grep "aarch")
    fi
}

pid() 
{
    arm
    if [ "$HOLER_ARM" = "" ]; then
        HOLER_PID=`ps -ef | grep -v grep | grep "$HOLER_APP" |awk '{print $2}'`
    else
        HOLER_PID=`ps -ef | grep -v grep | grep "$HOLER_APP" |awk '{print $1}'`
    fi
}

status() 
{
    pid
    if [ -n "$HOLER_PID" ]; then
        echo "Holer client PID <$HOLER_PID> is running."
    else
        echo "Holer client is stopped."
    fi
}

start() 
{
    pid
    if [ -n "$HOLER_PID" ]; then
        status
        return $HOLER_OK
    fi

    if [ ! -f "$JAVA_BIN" ]; then
        JAVA_BIN=`which java`
        if [ ! -f "$JAVA_BIN" ]; then
            JAVA_BIN=java
        fi
    fi

    $JAVA_BIN -jar $HOLER_APP >>$HOLER_LOG 2>&1 &
    status
}

stop() 
{
    pid
    if [ -z "$HOLER_PID" ]; then
        status
        return $HOLER_OK
    fi

    echo -e "Stopping the holer client PID <$HOLER_PID> ...\c"
    kill -9 $HOLER_PID >> $HOLER_LOG 2>&1
    status
}

# See how we were called.
case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status
    ;;
    restart)
        stop
        start
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit $HOLER_ERR
esac
